config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'todos/search'
  post 'todos/status_update'
  post 'todos/change_position'
  resources :todos
  resources :todos do
   resources :comments
 end
 resources :shares
  root 'todos#index'
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  has_many :shares
  has_many :comments, dependent: :destroy
  has_many :users, through: :shares, dependent: :destroy
  validates_presence_of :body

  scope :is_active, ->(keyword) { where('todos.active=?', keyword) }
  scope :user, ->(user) { where('shares.user_id=?', user.id) }
  scope :search, ->(keyword) { where('body LIKE ?', keyword).order(id: :desc) }
  scope :up, ->(current_todo) { select('todos.*,shares.priority').where('priority>?', current_todo[0].priority).is_active(current_todo[0].active?).order(priority: :asc).limit(1)[0] }
  scope :down, ->(current_todo) { select('todos.*,shares.priority').where('priority<?', current_todo[0].priority).is_active(current_todo[0].active?).order(priority: :desc).limit(1)[0] }
  scope :pagination, ->(keyword) { order(priority: :desc).paginate(page: keyword, per_page: 4) }

  # create todo and update priority
  def self.create_todo(todo_params, current_user)
    todo = Todo.new(todo_params)
    if todo.save
      Share.add_priority(todo, current_user)
      Todo.print_todos(true, todo_params, current_user).where(id: todo.id)[0]
    else
      { error: todo.errors.full_messages }
    end
  end

  # check whether search or index default index
  def self.check_params(params, current_user)
    if params.key?(:search)
      search
    elsif params.key?(:active)
      print_todos(params[:active] == 'active', params, current_user)
    else
      print_todos(true, params, current_user)
    end
  end

  # calling from each method
  def self.print_todos(status, params, current_user)
    if status == 0
      current_user.get_todos.pagination(params[:page])
    else
      current_user.get_active_todos(status).pagination(params[:page])
    end
  end

  # positionchange
  def self.position_update(params, current_user)
    current_todo =  current_user.get_current_todo(params[:id])
    case params[:arrow]
    when 'up'
      new_todo = current_user.get_next_todo(current_todo)
    when 'down'
      new_todo = current_user.get_previous_todo(current_todo)
    end
    if new_todo.present?
      position_change(current_todo, new_todo, current_user)
      arrow = params[:arrow]
    else
      { error: new_todo.errors.full_messages }
    end
  end

  # positionchange
  def self.position_change(current_todo, new_todo, current_user)
    new_priority = new_todo[:priority]
    current_priority = current_todo[0].priority
    current_todo[0].shares.where(user_id: current_user.id)[0].update(priority: new_priority)
    new_todo.shares.where(user_id: current_user.id)[0].update(priority: current_priority)
  end


  # search for index
  def self.search_index(current_user_id)
    user = User.find(current_user_id)
    if user.shares.order(:priority).empty?
      0
    else
      user.shares.order(:priority).last.priority
    end
  end

  # search
  def self.search_params(params, current_user)
    if params[:search].present?
      print_todos(0, params, current_user).search("%#{params[:search]}%").paginate(page: params[:page], per_page: 4)
    else
      print_todos(true, params, current_user)
    end
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  respond_to :js
  respond_to :html
  before_action :find_todo, only: %i[destroy status_update]
  before_action :find_todo_details, only: %i[show change_position]
  helper FormatedTime

  def index
    @list_todos = Todo.check_params(params, current_user)
  end

  # def new
  #   @todo = Todo.new
  # end

  # create todo and update priority added with last priority
  def create
    @todolist = Todo.create_todo(todo_params, current_user)
    @count = Todo.joins(:shares).user(current_user).is_active(true).count
  end

  # in show page search is null then normal show
  def search
    @list_todos = Todo.search_params(params, current_user)
  end

  # to change active status by checking db value when clicked tickbox
  def status_update
    @todo.update(active: !@todo.active?)
    @todo_details = @todo
  end

  # destroy parameters
  def destroy
    if @todo.present?
      @todo.destroy
      url = Rails.application.routes.recognize_path(request.referrer)
      redirect_to root_path if url[:action] == 'show'
    else
      @todo = { error: "already deleted" }
    end

  end

  # show todo link and comments
  def show
    @comments = User.joins(:comments).select('comments.*,users.*').where('comments.todo_id = ?', @todo_details.id)
    @shared_with = User.joins(:shares).select('users.name').todo_owner(params[:id], false)
  end

  # to change prority
  def change_position
    @arrow = Todo.position_update(params, current_user)
  end

  private

  def todo_params
    params.require(:todo).permit(:body, :active)
  end

  def find_todo
    @todo = Todo.find_by(id: params[:id])
  end

  def find_todo_details
    @todo_details = current_user.get_current_todo(params[:id])[0]
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_with scope: :todo,url:todos_path,id: "newtodo", remote: true do |form| %>
  <%= form.text_field :body , placeholder: "enter your todo", class: "createtodo"%>
<% end %>

app/views/todos/_todolist.html.erb
<div id="<%=todo.id%>" class="card posttodo" >
  <div class="row">
    <div class="col-8">
      <div class="card-text">
        <%= link_to todo.body, todo %>
      </div>
      <div class="row card-link ">
        <div class="col card-link text-muted"><%= format_time(todo.created_at) %></div>
      </div>

    </div>

    <div class="col-4 col-md-4 col-sm-4 col-lg-4 d-flex align-items-center border-0">
      <ul class="list-group list-group-horizontal-lg list-group-horizontal-sm list-group-horizontal border-0">
        <li class="list-group-items flex-fill border-0 up">

          <%= link_to todos_change_position_path(id:todo.id, arrow:"up"), data: { remote: true, url: url_for(action: :change_position), method: :post } do %>
          <i class="material-icons arrows">keyboard_arrow_up</i>
        <%end%>

      </li>

      <li class="list-group-items sflex-fill border-0 down">

        <%= link_to todos_change_position_path(id:todo.id, arrow:"down"), data: { remote: true, url: url_for(action: :change_position), method: :post } do %>
        <i class="material-icons arrows">keyboard_arrow_down</i>
      <% end %>

      </li>
    <%if todo.is_owner?%>
      <li class="list-group-items flex-fill border-0">
        <%= link_to todo_path(todo), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_todo' do %>
        <i class="material-icons arrows">clear</i>
    <%end%>

  </li>

  <li class="list-group-items flex-fill border-0">
    <%= link_to todos_status_update_path(id:todo.id), data: { remote: true, url: url_for(action: :status_update), method: :post } do %>
    <i class=" img-check material-icons <%=todo.active? ? "check" : "inactive"%>">check_circle</i>
    <%end%>
      </li>
    <%end%>
    </ul>
  </div>

  </div>

</div>

app/views/todos/change_position.js.erb
<% if @arrow.is_a?Hash %>
  $(".err_msg").show();
  $(".err_msg").html('<% @todolist[:error].each do |msg|%> <%=msg%></br> <%end%>').delay(3000).fadeOut();
<%else%>
$(".err_msg").hide();
var current_div = $("#<%=@todo_details.id%>");
if ("<%=@arrow%>" == "down"){
  var next_div = $("#<%=@todo_details.id%>").next();
  var current_todo = current_div.clone();
  var next_todo = next_div.clone();
  current_div.replaceWith(next_todo);
  next_div.replaceWith(current_todo);
}else{
  var prev_div = $("#<%=@todo_details.id%>").prev();
  var current_todo = current_div.clone();
  var prev_todo = prev_div.clone();
  current_div.replaceWith(prev_todo);
  prev_div.replaceWith(current_todo);
}
<%end%>
reset_arrow();

app/views/todos/create.js.erb
<% if @todolist.is_a?Hash %>
  $(".err_msg").show();
  $(".err_msg").html('<% @todolist[:error].each do |msg|%> <%=msg%></br> <%end%>').delay(3000).fadeOut();
<%else%>
$(".err_msg").hide();
if('<%=@count%>'== 1){
  $(".todolist").html("<%= escape_javascript render(:partial => 'todolist', :locals => { :todo => @todolist  }) %>");
}else{
  $(".todolist").prepend("<%= escape_javascript render(:partial => 'todolist', :locals => { :todo => @todolist }) %>");
}
<%end%>

$('.createtodo').val('');
reset_arrow();

app/views/todos/destroy.js.erb
<%if @todo.is_a?Hash%>
  $(".err_msg").show();
  $(".err_msg").html('<%= @todo[:error]%>').delay(2000).fadeOut();
  setTimeout("location.reload(true);",2000);
<%else%>
$(".err_msg").hide();
  $('#<%= j @todo.id %>').remove();
<%end%>
reset_arrow();

app/views/todos/index.html.erb
<div class="search-box">
  <%= text_field_tag :search , "", placeholder: "search",autofocus: true, class: "search"%>
</div>
<%= render 'form' %>
<div class="switch-field">
  <%= radio_button_tag 'active', 'active', false , data: { remote: true, method: :get } %>
  <label for="active_active">Active</label>
  <%= radio_button_tag 'active', 'inactive', false, data: { remote: true, method: :get } %>
  <label for="active_inactive">Inactive</label>
</div>
<div class="err_msg"></div>
<div class="apple_pagination"><%= will_paginate @list_todos %></div>
<div class="todolist">
  <% if !@list_todos.empty? %>

    <% @list_todos.each do |todo| %>
      <%= render 'todolist', todo: todo %>
    <% end %>
  <% else %>
    <div class="card posttodo">
      <div class="card-text">
        Nothing
      </div>
    </div>
  <% end %>

</div>

<div class="spinner-border loading" role="status">
  <p class="sr-only">Loading...</p>
</div>

<script>
  // $('.todolist').empty(); $('#active_active').click(); initialize active status as true
  $('#active_active').attr('checked', true);

  //search on key press
  $("#search").keyup(function () {
    $(".todolist").empty();
    $.ajax({
      url: '/todos/search',
      data: {
        search: $(this).val()
      }
    });
  });

  //radio button controll
  $("#active_active").click(function () {
    if ($("#active_active").attr('checked') != 'checked') {
      $(".todolist").empty();
    }
    $("#active_active").attr('checked', true);
    $('#active_inactive').attr('checked', false);

  });

  $("#active_inactive").click(function () {
    if ($("#active_inactive").attr('checked') != 'checked') {
      $(".todolist").empty();
    }
    $("#active_inactive").attr('checked', true);
    $('#active_active').attr('checked', false);

  });

  //loading animation
  $('.loading').hide();

  //remove arrows from first and last position
  function reset_arrow() {
    $('.up').removeClass("invisible");
    $('.down').removeClass("invisible");
    $('.up').first().addClass("invisible");
    $('.down').last().addClass("invisible");
  };

  //ajax for pagination
  $(function () {
    $('.pagination a').attr('data-remote', 'true')
  });

  //for infinite scroll functon // FIXME: not working
  function infinite_scroll(box) {
    if (box[0].scrollHeight - box.scrollTop() == box.outerHeight()) {
      $('.loading').show().fadeOut(1000);
      if ($('.pagination .next_page').hasClass('disabled')) {
        $('.loading').hide();
      }
      if (box.html() == "") {} else {
        $('.pagination .next_page')[0].click();
      }
    }
  };

  reset_arrow();

  //infinite scroll
  $('.todolist').on('scroll', function () {
    if ($('.todolist')[0].scrollHeight - $('.todolist').scrollTop() == $('.todolist').outerHeight()) {
      $('.loading').show().fadeOut(1000);
      if ($('.pagination .next_page').hasClass('disabled')) {
        $('.loading').hide();
      }
      if ($('.todolist').html() == "") {} else {
        $('.pagination .next_page')[0].click();
      }
    }
  });
</script>

app/views/todos/index.js.erb
$('.apple_pagination').html(`<%=will_paginate @list_todos %>`)

$('.todolist').append(`
  <% if !@list_todos.empty? %>
  <% @list_todos.each do |todo| %>
  <%= render 'todolist', todo: todo %>
  <% end %>
  <% end %>
`)
$('.pagination a').attr('data-remote', 'true')
reset_arrow();

app/views/todos/search.js.erb
<% url = Rails.application.routes.recognize_path(request.referrer)%>
<% if (url[:action] == 'show')%>
$('.apple_pagination').html(`<%=will_paginate @list_todos %>`)
$('.show-todos').append(`
  <% if !@list_todos.empty? %>
      <% @list_todos.each do |todo| %>
    <%= render 'todolist', todo: todo %>
    <% end %>
    <% else %>
    <div class="card posttodo">
    <div class="card-text">
    Nothing
    </div>
    </div>
    <% end %>
`);

<%else%>
$('.apple_pagination').html(`<%=will_paginate @list_todos %>`)
$('.todolist').append(`
  <% if !@list_todos.empty? %>
      <% @list_todos.each do |todo| %>
    <%= render 'todolist', todo: todo %>
    <% end %>
    <% else %>
    <div class="card posttodo">
    <div class="card-text">
    Nothing
    </div>
    </div>
    <% end %>
`);
<%end%>
  $('.pagination a').attr('data-remote', 'true')
  if ($(".search").val()){
    $('.up').addClass("invisible");
    $('.down').addClass("invisible");

  }else{
    reset_arrow();
  }

app/views/todos/show.html.erb
<div class="search-box">
  <%= text_field_tag :search , "", placeholder: "search",autofocus: true, class: "search"%>
</div>

<div class="back"><%= link_to "< Go back to home", root_path %></div>
<div class="show-todos"></div>
<div class="todo-details">
  <div class="row">
    <div class="col-11 todo-body">
      <%= @todo_details.body %>
    </div>
    <div class="col-1 flex-fill border-0">
      <%= link_to todo_path(@todo_details), method: :delete, data: { confirm: 'Are you sure?' }, :local => true, :class => 'delete_todo' do %>
      <i class="material-icons arrows">clear</i>
    <%end%>
  </div>
</div>
<div class="text-muted">
  <%= format_time(@todo_details.created_at) %>
</div>
<div class="task-complete">
  <p>Task Completion</p>
</div>
<div class="row task-status">
  <div class="progress col-11">
    <div class="progress-bar" role="progressbar" style="width: <%=@todo_details.task_status%>%;" aria-valuenow="<%=@todo_details.task_status%>" aria-valuemin="0" aria-valuemax="100">
      <span class="task-percentage"><%=@todo_details.task_status%>%</span></div>
  </div>
  <div class="flex-fill border-0 col-1 todo-img">
    <%= link_to todos_status_update_path(id:@todo_details.id), data: { remote: true, url: url_for(action: :status_update), method: :post } do %>
    <div class=" img-check material-icons">check_circle</div>
  <%end%>
</div>
</div>

<div class="share">
<p>
  <span class="sharedwith">Shared with:</span>
  <span class="shared-with">
    <%@shared_with.each do |user| %>
      <%= render '/shares/shared_users', user: user %>
    <%end%>
  </span>
</p>
</div>

<div>
<button type="button" class="btn btn-outline-secondary">Share this</button>
</div>

</div>

<div id="overlay">
<div class="user-list">
<div class="add-people">
  Add people to this task
</div>
<div class="shared-users">
  <%unless @users.nil?%>
    <%@users.each do |user|%>
      <%= render '/shares/sharelist', user: user%>
    <%end%>
  <%end%>

</div>
<div class="user-footer">
  <div class="save-share">
    <button type="button" class="save-share-btn">Save</button>
  </div>
  <div class="cancel-share" onclick="off()">
    Cancel
  </div>
</div>
</div>
</div>

<div class="comment-list">
<% @comments.each do |comment|%>
<%= render '/comments/comments', comment: comment%>
<% end %>
</div>

<div class="comment-box">
<%= render '/comments/form' %>
</div>

<script>
var todo_id = <%= @todo_details.id %>;
var current_user_id = <%= @todo_details.user_id %>;
var todo_owner = <%= @todo_details.is_owner %>;
var is_todo_active = <%= @todo_details.active? %>;

function off() {
document.getElementById("overlay").style.display = "none";
}

//add class during startup for ok icon
if (is_todo_active) {
$(".img-check").addClass("check");
} else {
$(".img-check").addClass("inactive");
}

//hide from other users
if (!todo_owner) {
$('.delete_todo, .todo-img, .btn').hide();
}

//change the progress when clicked
$('.progress').click(function (event) {
var currentProgress = $('.progress-bar').attr('aria-valuenow');
var xPosition = event.pageX - $(this).offset().left;
var width = (((($(this).children())[0])["style"])["width"]);
var newProgress = Math.round((xPosition / 575) * 100);
if (newProgress <= 100 && newProgress >= 0) {

  //remotely sent status to comment controller
  $.ajax({
    type: 'POST',
    url: '/todos/' + todo_id + '/comments',
    data: {
      new_status: newProgress,
      old_status: currentProgress
    },
    success: function () {
      if (width != newProgress + "%") {
        $('.progress-bar').css('width', newProgress + '%');
        $('.progress-bar').attr('aria-valuenow', newProgress);
        $('.progress-bar').text(newProgress + "%");
      }
    }
  });
}
});

//view users to share and show overlay effect
$(".btn").click(function () {
document.getElementById("overlay").style.display = "block";
$.ajax({
  type: 'GET',
  url: '/shares/',
  data: {
    todo_id: todo_id,
    current_user_id: current_user_id
  }
});
});

// change status of the image ok button
$(".img-check").click(function () {
var is_active = $(".img-check").hasClass("inactive")
if (is_active) {
  $(".img-check").removeClass("inactive");
  $(".img-check").addClass("check");
} else {
  $(".img-check").removeClass("check");
  $(".img-check").addClass("inactive");
}
});

//save button clicked
$(".save-share-btn").click(function () {
off();
var users = new Array();
$("input[name='user-check']:checked").each(function (i) {
  users.push($(this).attr("id"));
});

if (users.length == 0) {
  users.push(0);
}
$.ajax({
  type: 'POST',
  url: '/shares/',
  data: {
    user_array: users,
    todo_id: todo_id
  }
});
});

//Remove comm from last name
$(".comma").last().remove();

//for search field
$("#search").keyup(function () {

if (($("#search").val()) == '') {
  $(".show-todos").hide();
  $('.todo-details,.overlay,.comment-list,.comment-box').show();
} else {
  $(".show-todos").empty();
  $(".show-todos").show();
  $('.todo-details,.overlay,.comment-list,.comment-box').hide();
}
$.ajax({
  url: '/todos/search',
  data: {
    search: $(this).val()
  }
});
});
</script>

app/views/todos/status_update.js.erb
is_inactive = $('#<%= j @todo_details.id %> .img-check').hasClass("inactive");
if (is_inactive){
  $('#<%= j @todo_details.id %> .img-check').removeClass("inactive").addClass("check");
}
else{
    $('#<%= j @todo_details.id %> .img-check').addClass("inactive");
}

// reset_arrow();